# Generated by Django 2.2.7 on 2019-11-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetadata',
            name='age_range',
            field=models.CharField(choices=[('18', '18-24'), ('25', '25-34'), ('35', '35-44'), ('45', '45-54'), ('55', '55-64'), ('65', '65+')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non binary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='user_type',
            field=models.CharField(choices=[('global', 'Global Administrator'), ('group', 'Hotel Group Administrator'), ('hotel', 'Hotel Administrator'), ('user', 'End User')], default='user', max_length=20),
        ),
    ]
