# Generated by Django 2.2.7 on 2019-11-19 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191119_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermetadata',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18', '18-24'), ('25', '25-34'), ('35', '35-44'), ('45', '45-54'), ('55', '55-64'), ('65', '65+')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non binary')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='hotel',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='cms.Hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='hotel_group',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='cms.HotelGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', upload_to='upload/images/'),
            preserve_default=False,
        ),
    ]
