# Generated by Django 2.2.7 on 2019-11-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191119_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermetadata',
            name='user_type',
        ),
    ]
