# Generated by Django 2.2.7 on 2019-11-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usermetadata_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
