# Generated by Django 2.2 on 2020-02-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usermetadata_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='uid',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
