# Generated by Django 2.2 on 2020-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usermetadata_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetadata',
            name='uid',
            field=models.CharField(blank=True, max_length=28, null=True, unique=True),
        ),
    ]
