# Generated by Django 2.2.7 on 2019-11-19 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelgallery',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.Rating'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.HotelGroup'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
