# Generated by Django 2.2.7 on 2019-11-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20191119_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Hotel',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Room',
            new_name='room',
        ),
    ]
