# Generated by Django 2.2.7 on 2019-11-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20191119_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='geo_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hotelgroup',
            name='head_office_address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelgroup',
            name='head_office_city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hotelgroup',
            name='head_office_country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hotelgroup',
            name='head_office_geolocation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelgroup',
            name='head_office_postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hotelgroup',
            name='hotel_group_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='meeting_room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('service', 'Service'), ('co_share', 'Co-share'), ('meeting_room', 'Meeting Room')], default='service', max_length=20),
        ),
    ]
