# Generated by Django 2.2 on 2019-12-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_booking_hotel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelgallery',
            name='rating',
        ),
    ]
