# Generated by Django 2.2 on 2019-12-11 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_remove_hotelgallery_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.TextField(choices=[('1', 'Confirmed'), ('2', 'Cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Room'),
        ),
    ]
