# Generated by Django 2.2 on 2019-12-11 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20191211_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Hotel'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hotel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.HotelGroup'),
        ),
        migrations.AlterField(
            model_name='service',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
