# Generated by Django 2.2 on 2020-01-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20191211_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='hotelgroup',
            name='head_office_geolocation',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hotel',
            name='long_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hotel',
            name='short_description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='hotelgroup',
            name='head_office_latitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hotelgroup',
            name='head_office_longitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.TextField(choices=[('0', 'Cancelled'), ('1', 'Confirmed'), ('2', 'Checked In'), ('3', 'Checked Out')], max_length=100),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Hotel')),
                ('hotel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.HotelGroup')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Icon')),
            ],
        ),
    ]
