# Generated by Django 2.2 on 2020-01-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20200128_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='contact_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
