# Generated by Django 2.2 on 2020-02-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_hotel_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ibe_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ibe_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotelgroup',
            name='head_office_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotelgroup',
            name='head_office_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=10),
        ),
    ]
