# Generated by Django 2.2 on 2020-02-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20200207_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.ServiceCategory'),
        ),
    ]
