# Generated by Django 2.2 on 2020-02-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20200210_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Hotel'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='hotel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.HotelGroup'),
        ),
    ]
