# Generated by Django 2.2 on 2020-02-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_subscriber_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_unit',
            field=models.CharField(choices=[('hour', 'Per hour'), ('day', 'Per day'), ('week', 'Per week'), ('month', 'Per month')], default='hour', max_length=20, unique=True),
        ),
    ]
