# Generated by Django 2.2 on 2020-02-11 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_auto_20200211_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Subscription'),
        ),
    ]
