# Generated by Django 2.2 on 2020-07-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='upload/images/'),
        ),
    ]
