# Generated by Django 2.2 on 2019-12-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_remove_hotelgallery_rating'),
        ('mobile', '0003_auto_20191119_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='hotel_gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.HotelGallery'),
        ),
    ]
